name: gerencia_net_plus
description: A Dart plugin that allows a better way to connect to Gerencianet - Efí Api.
version: 0.0.1
repository: https://github.com/cardosoOReis/gerencia_net_plus.git
environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  dio: ^5.2.1+1
  dio_http2_adapter: ^2.3.0
  equatable: ^2.0.5
  intl: ^0.18.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  dotenv: ^4.1.0
  import_sorter: ^4.6.0
  lints: ^2.0.0
  test: ^1.21.0
