name: gerencia_net_plus
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.1.0-169.0.dev

# Add regular dependencies here.
dependencies:
  dio: ^5.2.1+1
  dio_http2_adapter: ^2.3.0
  dotenv: ^4.1.0
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
